import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import tseslint from 'typescript-eslint'

const sharedPlugins = {
  'react-hooks': reactHooks,
  'react-refresh': reactRefresh,
}

const sharedRules = {
  ...reactHooks.configs.recommended.rules,
  'no-empty': ['error', { allowEmptyCatch: true }],
  'react-refresh/only-export-components': [
    'warn',
    { allowConstantExport: true },
  ],
}

export default tseslint.config(
  {
    ignores: [
      'dist/**',
      'coverage/**',
      'node_modules/**',
      '.dbg/**',
      '.version-backups/**',
      'MangooTech-Build/**',
      'MangooTech-Dist/**',
      'tmpclone/**',
      'clean-repo/**',
      'mini-boutique-3008/**',
      'mini-boutique-nouvelle-3008/**',
      'mini-boutique-propre/**',
      'mini-boutique-simple-3008/**',
      'mini-boutique-standalone/**',
      'mangootech-platform-complete/**',
      'js/**',
      'scripts/**',
      'server/scripts/**',
      'server/servers/signaling-server.js',
      'server/servers/live-shopping-chat-server.js',
      'server/servers/start-webrtc-servers.js',
      'server/servers/turn-server.js',
      'server/servers/voip-server.js',
      'server/servers/voip-sip-server.js',
      'server/servers/webrtc-server.js',
      'server/add-current-user-admin.js',
      'server/sip-gateway.js',
      'server/webrtc-server.js',
      'server/webrtc-sip-gateway.js',
      'server/webrtc-sip-gateway-advanced.js',
      'src/App-backup.jsx',
      'src/App-simple.jsx',
      'src/AppMinimal.jsx',
      'src/AppMinimalClean.jsx',
      'src/AppOptimized.jsx',
      'src/AppTotallyIsolated.jsx',
      'src/main.minimal.jsx',
      'src/main.totally.isolated.jsx',
      'src/pages/**/*Test*.js',
      'src/pages/**/*Test*.jsx',
      'src/pages/**/*Test*.ts',
      'src/pages/**/*Test*.tsx',
      'server/routes/test-*.js',
      'server/servers/test-*.js',
      'advanced-*.js',
      'analyse-*.js',
      'analyse-*.mjs',
      'appliquer-*.cjs',
      'apply-*.cjs',
      'auto-*.js',
      'auto-*.mjs',
      'auto-*.cjs',
      'automated-*.js',
      'browser-*.js',
      'button-*.js',
      'check-*.js',
      'clean-*.js',
      'console-script-*.js',
      'create-*.js',
      'dashboard-*.js',
      'debug-*.js',
      'debug-*.cjs',
      'debug_*.js',
      'diagnose-*.js',
      'diagnostic-*.js',
      'diagnostic-*.cjs',
      'fix-*.js',
      'fix-*.cjs',
      'force-*.js',
      'generate-*.js',
      'generate-*.cjs',
      'insert-*.js',
      'insert-*.mjs',
      'mini-boutique-*.js',
      'monitor-*.js',
      'multi-port.config.js',
      'nettoyage-*.js',
      'server-test*.js',
      'server-test*.mjs',
      'serveur-*.js',
      'serveur-*.mjs',
      'simple-test.mjs',
      'start-*.js',
      'start-*.mjs',
      'test-*.js',
      'test-*.mjs',
      'test-*.cjs',
      'verification-*.js',
      'verify-*.cjs',
    ],
  },
  {
    extends: [js.configs.recommended],
    files: ['**/*.{js,jsx,mjs,cjs}'],
    languageOptions: {
      ecmaVersion: 2020,
      sourceType: 'module',
      parserOptions: {
        ecmaFeatures: {
          jsx: true,
        },
      },
      globals: {
        ...globals.browser,
        ...globals.node,
      },
    },
    plugins: sharedPlugins,
    rules: {
      ...sharedRules,
      'no-unused-vars': ['error', {
        argsIgnorePattern: '^_',
        varsIgnorePattern: '^React$|^_',
        caughtErrorsIgnorePattern: '^_|^e$|^err$|^error$',
      }],
    },
  },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ['**/*.{ts,tsx}'],
    languageOptions: {
      ecmaVersion: 2020,
      parserOptions: {
        ecmaFeatures: {
          jsx: true,
        },
      },
      globals: {
        ...globals.browser,
        ...globals.node,
      },
    },
    plugins: sharedPlugins,
    rules: {
      ...sharedRules,
      '@typescript-eslint/no-unused-vars': ['error', {
        argsIgnorePattern: '^_',
        varsIgnorePattern: '^_',
        caughtErrorsIgnorePattern: '^_|^e$|^err$|^error$',
      }],
      '@typescript-eslint/no-explicit-any': 'off',
    },
  },
  {
    files: ['**/*.{jsx,tsx}'],
    rules: {
      'no-unused-vars': 'off',
      '@typescript-eslint/no-unused-vars': 'off',
    },
  },
)
